---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: execute export to CSV scripts
      delegate_to: mother
      shell: "mysql --user={{ mysql_db_local_root_user }} --password={{ mysql_db_local_root_password }} -A {{ mysql_old_db_local_name }} < ../scripts/database-exports/full-opengest-v1-export-queries.sql"
