---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: execute export to CSV scripts
      shell: "mysql --user={{ mysql_db_remote_root_user }} --password={{ mysql_db_remote_root_password }} -A {{ mysql_old_db_remote_name }} < {{ playbook_dir }}/../scripts/database-exports/full-opengest-v1-export-queries.sql"
    - name: move exported CSV files to import directory
      become: true
      shell: "sudo chown {{ remote_system_user }} /tmp/*.csv && sudo chgrp {{ remote_system_group }} /tmp/*.csv && chmod 644 /tmp/*.csv && mv /tmp/*.csv {{ playbook_dir }}/../csv/"
