---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: coopy old uploads to new local directory
      delegate_to: mother
      shell: "php app/console app:import:enterprise app/csv/enterprises.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
