imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc
    serializer:
        cache: serializer.mapping.cache.apc

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver:   apcu
        query_cache_driver:    apcu

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:      rotating_file
            path:      "%kernel.logs_dir%/%kernel.environment%.log"
            level:     debug
            max_files: 10
        console:
            type:  console
