services:
    app.service_repository:
        class: AppBundle\Repository\ServiceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Service
    app.vehicle_category_repository:
        class: AppBundle\Repository\VehicleCategoryRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:VehicleCategory
    app.work_repository:
        class: AppBundle\Repository\WorkRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Work
    app.complement_repository:
        class: AppBundle\Repository\ComplementRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Complement
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:User
    app.operator_repository:
        class: AppBundle\Repository\OperatorRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Operator
    app.repositories_manager:
        class: AppBundle\Manager\RepositoriesManager
        arguments:
            - "@app.service_repository"
            - "@app.vehicle_category_repository"
            - "@app.user_repository"
            - "@app.operator_repository"
