imports:
    - { resource: services/admins/admin.yml }

services:
# Pdf
    app.pdf_engine:
        class: AppBundle\Service\PdfEngineService
        arguments: [ "%mailer_url_base%", "%project_admin_title%" ]
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments: [ "@swiftmailer.mailer" ]
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments: [ "@app.courier", "@twig", "%mailer_destination%", "%mailer_url_base%" ]
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@security.token_storage", "@app.vehicle_category_repository", "@app.service_repository", "@app.work_repository", "@app.complement_repository", "@router" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
    app.frontend_vehicle_category_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createVehicleCategoryMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: vehicle_category }
    app.frontend_service_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createServiceMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: service }
    app.frontend_footer_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createFooterMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: footer }
    app.frontend_sitemap_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createSitemapMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: sitemap }
# Sitemap
    app.sitemap:
        class: AppBundle\Listener\SitemapListener
        arguments: [ "@router", "@app.frontend_menu_builder" ]
        tags: [ { name: "presta.sitemap.listener" } ]
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
# Block
    app.block.contact_message:
        class: AppBundle\Block\ContactMessageBlock
        arguments: [ "app.block.contact_message", "@templating", "@doctrine.orm.entity_manager" ]
        tags:
            - { name: sonata.block }
    app.block.vehicle_checking:
        class: AppBundle\Block\VehicleCheckingBlock
        arguments: [ "app.block.vehicle_checking", "@templating", "@app.vehicle_checking_repository", "@security.token_storage" ]
        tags:
            - { name: sonata.block }
    app.block.operator_checking:
        class: AppBundle\Block\OperatorCheckingBlock
        arguments: [ "app.block.operator_checking", "@templating", "@app.operator_checking_repository", "@security.token_storage" ]
        tags:
            - { name: sonata.block }
    app.block.operator_absence:
        class: AppBundle\Block\OperatorAbsenceBlock
        arguments: [ "app.block.operator_absence", "@templating", "@app.operator_absence_repository", "@security.token_storage" ]
        tags:
            - { name: sonata.block }
# File
    app.file_service:
        class: AppBundle\Service\FileService
        arguments: [ "@vich_uploader.templating.helper.uploader_helper", "%kernel.root_dir%" ]
# Guard
    app.guard_service:
        class: AppBundle\Service\GuardService
        arguments: [ "@security.authorization_checker" ]
# Form
    app.form_user_default_enterprise:
        class: AppBundle\Form\UserDefaultEnterpriseForm
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]
        tags:
            - { name: form.type }
# Voters
    app.voter_enterprise:
        class: AppBundle\Security\EnterpriseVoter
        tags:
            - { name: security.voter }
        public: false
    app.voter_operator:
        class: AppBundle\Security\OperatorVoter
        tags:
            - { name: security.voter }
        public: false
    app.voter_operator_checking:
        class: AppBundle\Security\OperatorCheckingVoter
        tags:
            - { name: security.voter }
        public: false
    app.voter_vehicle:
        class: AppBundle\Security\VehicleVoter
        tags:
            - { name: security.voter }
        public: false
    app.voter_vehicle_checking:
        class: AppBundle\Security\VehicleCheckingVoter
        tags:
            - { name: security.voter }
        public: false
    app.voter_partner:
        class: AppBundle\Security\PartnerVoter
        tags:
            - { name: security.voter }
        public: false
# Managers
    app.year_choices_manager:
        class: AppBundle\Manager\YearChoicesManager
    app.invoice_manager:
        class: AppBundle\Manager\InvoiceManager
        arguments: [ "@app.sale_invoice_repository"]
    app.delivery_note_manager:
        class: AppBundle\Manager\DeliveryNoteManager
        arguments: [ "@app.sale_delivery_note_repository"]

