services:
# Sonata Admin
    app.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~ , AppBundle\Entity\Service, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servei", group: "Web" }
    app.admin.work:
        class: AppBundle\Admin\WorkAdmin
        arguments: [ ~ , AppBundle\Entity\Work, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Treball", group: "Web" }
    app.admin.work_image:
        class: AppBundle\Admin\WorkImageAdmin
        arguments: [ ~ , AppBundle\Entity\WorkImage, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Imatge Treball", group: "Web", show_in_dashboard: false }
    app.admin.vehicle_category:
        class: AppBundle\Admin\VehicleCategoryAdmin
        arguments: [ ~ , AppBundle\Entity\VehicleCategory, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoria Vehicle", group: "Web" }
    app.admin.vehicle:
        class: AppBundle\Admin\VehicleAdmin
        arguments: [ ~ , AppBundle\Entity\Vehicle, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Vehicle", group: "Web" }
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Usuaris" }
# Menu
    app.frontend_menu_builder:
        class: AppBundle\Menu\FrontendMenuBuilder
        arguments: [ "@knp_menu.factory", "@security.authorization_checker", "@security.token_storage", "@app.vehicle_category_repository" ]
    app.frontend_top_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createTopMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: top }
    app.frontend_vehicle_category_menu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.frontend_menu_builder", createVehicleCategoryMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: vehicle_category }
# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
