services:
# Sonata Admin
    app.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~ , AppBundle\Entity\Service, ~, "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servei", group: "Web" }
