 # Sonata Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:  ~
        sonata.user.block.menu:         ~
        sonata.block.service.text:      ~
        app.block.contact_message:      ~
        app.block.operator_checking:    ~
        app.block.operator_absence:     ~
        app.block.vehicle_checking:     ~

# Sonata User
sonata_user:
    security_acl: true
    manager_type: orm

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     AppBundle\Entity\User
    group:
        group_class:   AppBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# Admin
sonata_admin:
    title:      "%project_web_title%"
    title_logo: "/bundles/app/img/logo_romani_horizontal.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
        edit:   "::Admin/edit.html.twig"
#        show:   "::Admin/show.html.twig"
    dashboard:
        groups:
            Web:
                icon: "<i class='fa fa-chrome'></i>"
            Contactes:
                icon: "<i class='fa fa-envelope'></i>"
            Operaris:
                icon: "<i class='fa fa-users'></i>"
            Vehicles:
                icon: "<i class='fa fa-truck'></i>"
            Tercers:
                icon: "<i class='fa fa-user'></i>"
            Empreses:
                icon: "<i class='fa fa-building'></i>"
            Vendes:
                icon: "<i class='fa fa-eur'></i>"
            Administracio:
                label: "Administració"
                icon: "<i class='fa fa-briefcase'></i>"

        blocks:
            -
                position: top
                type: app.block.operator_checking
                class: "col-md-3"
            -
                position: top
                type: app.block.operator_absence
                class: "col-md-3"
            -
                position: top
                type: app.block.vehicle_checking
                class: "col-md-3"
            -
                position: top
                type: app.block.contact_message
                class: "col-md-3"
            -
                position: top
                type: sonata.block.service.text
                class: "col-md-12"
                settings:
                    content: >
                        <hr style="margin-bottom:0">
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-3"
                settings:
                    groups: [ Web ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-3"
                settings:
                    groups: [ Contactes, Vehicles ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-3"
                settings:
                    groups: [ Operaris ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: "col-md-3"
                settings:
                    groups: [ Empreses, Administracio ]
            -
                position: bottom
                type: sonata.block.service.text
                class: "col-md-12"
                settings:
                    content: >
                        <hr style="margin-top:40px;border-top:solid 1px #d2d6de">
                        <h5 style="margin:0 0 25px 0"><i class="fa fa-info-circle" aria-hidden="true"></i> Per rebre assistència tècnica o ajuda envieu un missatge a <a href="mailto:suport@flux.cat?subject=Ajuda administrador de continguts %project_web_title%">suport@flux.cat</a></h5>
