 # Sonata Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:   ~
        sonata.user.block.menu:          ~
        sonata.block.service.text:       ~
        app.block.contact_message:       ~
        app.block.operator_checking:     ~
        app.block.operator_absence:      ~
        app.block.vehicle_checking:      ~
        app.block.sale_request_today:    ~
        app.block.sale_request_tomorrow: ~
        app.block.sale_request_next:     ~

# Sonata User
sonata_user:
    security_acl: true
    manager_type: orm

# FOS User
fos_user:
    db_driver:     orm
    firewall_name: admin
    user_class:    AppBundle\Entity\Setting\User
    group:
        group_class:   AppBundle\Entity\Setting\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# Admin
sonata_admin:
    title:      "%project_web_title%"
    title_logo: "/bundles/app/img/logo_romani.png"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout:        "::Admin/layout.html.twig"
        edit:          "::Admin/edit.html.twig"
        show:          "::Admin/show.html.twig"
        pager_results: "::Admin/pager_results.html.twig"
    dashboard:
        groups:
            Web:
                icon: "<i class='fa fa-chrome'></i>"
            Operaris:
                icon: "<i class='fa fa-users'></i>"
            Vehicles:
                icon: "<i class='fa fa-truck'></i>"
            Tercers:
                icon: "<i class='fa fa-user'></i>"
            Empreses:
                icon: "<i class='fa fa-building'></i>"
            Vendes:
                icon: "<i class='fa fa-eur'></i>"
            Configuracio:
                label: "Configuració"
                icon: "<i class='fa fa-briefcase'></i>"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: "col-md-12"
                settings:
                    content: >
                        <h4 style="margin-top:0" class="c-grey"><strong>Revisions</strong></h4>
            -
                position: top
                type: app.block.operator_checking
                class: "col-md-3"
            -
                position: top
                type: app.block.operator_absence
                class: "col-md-3"
            -
                position: top
                type: app.block.vehicle_checking
                class: "col-md-3"
            -
                position: top
                type: app.block.contact_message
                class: "col-md-3"
            -
                position: top
                type: sonata.block.service.text
                class: "col-md-12"
                settings:
                    content: >
                        <h4 class="c-grey"><strong>Peticions</strong></h4>
            -
                position: top
                type: app.block.sale_request_today
                class: "col-md-4"
            -
                position: top
                type: app.block.sale_request_tomorrow
                class: "col-md-4"
            -
                position: top
                type: app.block.sale_request_next
                class: "col-md-4"
