services:
# Sonata Admin
    app.admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [ ~ , AppBundle\Entity\Service, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servei", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.work:
        class: AppBundle\Admin\WorkAdmin
        arguments: [ ~ , AppBundle\Entity\Work, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Treball", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.work_image:
        class: AppBundle\Admin\WorkImageAdmin
        arguments: [ ~ , AppBundle\Entity\WorkImage, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Imatge Treball", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    app.admin.vehicle_category:
        class: AppBundle\Admin\VehicleCategoryAdmin
        arguments: [ ~ , AppBundle\Entity\VehicleCategory, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoria Vehicle", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.vehicle:
        class: AppBundle\Admin\VehicleAdmin
        arguments: [ ~ , AppBundle\Entity\Vehicle, AppBundle:Admin\VehicleAdmin, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Vehicle", group: "Vehicles", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.complement:
        class: AppBundle\Admin\ComplementAdmin
        arguments: [ ~ , AppBundle\Entity\Complement, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Accesori", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.contact_message:
        class: AppBundle\Admin\ContactMessageAdmin
        arguments: [ ~, AppBundle\Entity\ContactMessage, AppBundle:Admin\ContactMessageAdmin, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge de Contacte", group: "Contactes", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.province:
        class: AppBundle\Admin\ProvinceAdmin
        arguments: [ ~, AppBundle\Entity\Province, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Administracio", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.city:
        class: AppBundle\Admin\CityAdmin
        arguments: [ ~, AppBundle\Entity\City, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Ciutat", group: "Administracio", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.enterprise:
        class: AppBundle\Admin\EnterpriseAdmin
        arguments: [ ~, AppBundle\Entity\Enterprise, AppBundle:Admin\EnterpriseAdmin, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Empresa", group: "Administracio", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator:
        class: AppBundle\Admin\OperatorAdmin
        arguments: [ ~, AppBundle\Entity\Operator, AppBundle:Admin\OperatorAdmin, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Operador", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_checking_type:
        class: AppBundle\Admin\OperatorCheckingTypeAdmin
        arguments: [ ~, AppBundle\Entity\OperatorCheckingType, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus revisió", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_checking:
        class: AppBundle\Admin\OperatorCheckingAdmin
        arguments: [ ~, AppBundle\Entity\OperatorChecking, AppBundle:Admin\OperatorCheckingAdmin, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Revisió", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_absence_type:
        class: AppBundle\Admin\OperatorAbsenceTypeAdmin
        arguments: [ ~, AppBundle\Entity\OperatorAbsenceType, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus absència", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_absence:
        class: AppBundle\Admin\OperatorAbsenceAdmin
        arguments: [ ~, AppBundle\Entity\OperatorAbsence, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Absència", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.vehicle_checking_type:
        class: AppBundle\Admin\VehicleCheckingTypeAdmin
        arguments: [ ~, AppBundle\Entity\VehicleCheckingType, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus revisió", group: "Vehicles", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.vehicle_checking:
        class: AppBundle\Admin\VehicleCheckingAdmin
        arguments: [ ~, AppBundle\Entity\VehicleChecking, ~, "@liip_imagine.cache.manager", "@app.repositories_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Revisió", group: "Vehicles", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, AppBundle:Admin\UserAdmin, "@fos_user.user_manager", "@app.repositories_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Administracio", label_translator_strategy: "sonata.admin.label.strategy.noop" }
