<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20190311173246 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE invoices_deliveynotes (sale_invoice_id INT NOT NULL, sale_delivery_note_id INT NOT NULL, INDEX IDX_F8A177F8D4DD15B9 (sale_invoice_id), INDEX IDX_F8A177F89C1DE698 (sale_delivery_note_id), PRIMARY KEY(sale_invoice_id, sale_delivery_note_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE invoices_deliveynotes ADD CONSTRAINT FK_F8A177F8D4DD15B9 FOREIGN KEY (sale_invoice_id) REFERENCES sale_invoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoices_deliveynotes ADD CONSTRAINT FK_F8A177F89C1DE698 FOREIGN KEY (sale_delivery_note_id) REFERENCES sale_delivery_note (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE digital_tachograph');
        $this->addSql('ALTER TABLE sale_invoice CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE series_id series_id INT DEFAULT NULL, CHANGE total total DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sale_request CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE invoice_to_id invoice_to_id INT DEFAULT NULL, CHANGE vehicle_id vehicle_id INT DEFAULT NULL, CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE tariff_id tariff_id INT DEFAULT NULL, CHANGE attended_by_id attended_by_id INT DEFAULT NULL, CHANGE secondary_vehicle_id secondary_vehicle_id INT DEFAULT NULL, CHANGE height height INT DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT NULL, CHANGE utensils utensils VARCHAR(255) DEFAULT NULL, CHANGE hour_price hour_price DOUBLE PRECISION DEFAULT NULL, CHANGE minium_hours minium_hours DOUBLE PRECISION DEFAULT NULL, CHANGE displacement displacement DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE contact_person_name contact_person_name VARCHAR(255) DEFAULT NULL, CHANGE contact_person_phone contact_person_phone VARCHAR(255) DEFAULT NULL, CHANGE end_service_time end_service_time TIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46AD4DD15B9');
        $this->addSql('DROP INDEX IDX_3FA6B46AD4DD15B9 ON sale_delivery_note');
        $this->addSql('ALTER TABLE sale_delivery_note DROP sale_invoice_id, CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE building_site_id building_site_id INT DEFAULT NULL, CHANGE order_id order_id INT DEFAULT NULL, CHANGE collection_document_id collection_document_id INT DEFAULT NULL, CHANGE activity_line_id activity_line_id INT DEFAULT NULL, CHANGE discount discount DOUBLE PRECISION DEFAULT NULL, CHANGE collection_term collection_term INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sale_request_has_delivery_note CHANGE sale_request_id sale_request_id INT DEFAULT NULL, CHANGE sale_delivery_note_id sale_delivery_note_id INT DEFAULT NULL, CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE total_hours_morning total_hours_morning DOUBLE PRECISION DEFAULT NULL, CHANGE price_hour_morning price_hour_morning DOUBLE PRECISION DEFAULT NULL, CHANGE amount_morning amount_morning DOUBLE PRECISION DEFAULT NULL, CHANGE total_hours_afternoon total_hours_afternoon DOUBLE PRECISION DEFAULT NULL, CHANGE price_hour_afternoon price_hour_afternoon DOUBLE PRECISION DEFAULT NULL, CHANGE amount_afternoon amount_afternoon DOUBLE PRECISION DEFAULT NULL, CHANGE total_hours_night total_hours_night DOUBLE PRECISION DEFAULT NULL, CHANGE price_hour_night price_hour_night DOUBLE PRECISION DEFAULT NULL, CHANGE amount_night amount_night DOUBLE PRECISION DEFAULT NULL, CHANGE total_hours_early_morning total_hours_early_morning DOUBLE PRECISION DEFAULT NULL, CHANGE price_hour_early_morning price_hour_early_morning DOUBLE PRECISION DEFAULT NULL, CHANGE amount_early_morning amount_early_morning DOUBLE PRECISION DEFAULT NULL, CHANGE total_hours_displacement total_hours_displacement DOUBLE PRECISION DEFAULT NULL, CHANGE price_hour_displacement price_hour_displacement DOUBLE PRECISION DEFAULT NULL, CHANGE amount_displacement amount_displacement DOUBLE PRECISION DEFAULT NULL, CHANGE iva_type iva_type DOUBLE PRECISION DEFAULT NULL, CHANGE retention_type retention_type DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sale_delivery_note_line CHANGE delivery_note_id delivery_note_id INT DEFAULT NULL, CHANGE units units DOUBLE PRECISION DEFAULT NULL, CHANGE total total DOUBLE PRECISION DEFAULT NULL, CHANGE discount discount DOUBLE PRECISION DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sale_tariff CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE price_hour price_hour DOUBLE PRECISION DEFAULT NULL, CHANGE minium_hours minium_hours DOUBLE PRECISION DEFAULT NULL, CHANGE minium_holiday_hours minium_holiday_hours DOUBLE PRECISION DEFAULT NULL, CHANGE displacement displacement DOUBLE PRECISION DEFAULT NULL, CHANGE increase_for_holidays increase_for_holidays DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle_digital_tachograph CHANGE vehicle_id vehicle_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle_category CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle_checking_type CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle_checking CHANGE vehicle_id vehicle_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE vehicle CHANGE vehicle_category_id vehicle_category_id INT DEFAULT NULL, CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE short_description short_description VARCHAR(255) DEFAULT NULL, CHANGE link link VARCHAR(255) DEFAULT NULL, CHANGE attatchment_pdf attatchment_pdf VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE enterprise_transfer_account CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE iban iban VARCHAR(255) DEFAULT NULL, CHANGE swift swift VARCHAR(255) DEFAULT NULL, CHANGE bank_code bank_code VARCHAR(255) DEFAULT NULL, CHANGE office_number office_number VARCHAR(255) DEFAULT NULL, CHANGE control_digit control_digit VARCHAR(255) DEFAULT NULL, CHANGE account_number account_number VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE activity_line CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE enterprise_group_bounty CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE enterprise_holidays CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE enterprise CHANGE city_id city_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE phone1 phone1 VARCHAR(255) DEFAULT NULL, CHANGE phone2 phone2 VARCHAR(255) DEFAULT NULL, CHANGE phone3 phone3 VARCHAR(255) DEFAULT NULL, CHANGE fax fax VARCHAR(255) DEFAULT NULL, CHANGE www www VARCHAR(255) DEFAULT NULL, CHANGE logo logo VARCHAR(255) DEFAULT NULL, CHANGE deed_of_incorporation deed_of_incorporation VARCHAR(255) DEFAULT NULL, CHANGE tax_identification_number_card tax_identification_number_card VARCHAR(255) DEFAULT NULL, CHANGE tc1receipt tc1receipt VARCHAR(255) DEFAULT NULL, CHANGE tc2receipt tc2receipt VARCHAR(255) DEFAULT NULL, CHANGE ss_registration ss_registration VARCHAR(255) DEFAULT NULL, CHANGE ss_payment_certificate ss_payment_certificate VARCHAR(255) DEFAULT NULL, CHANGE rc1insurance rc1insurance VARCHAR(255) DEFAULT NULL, CHANGE rc2insurance rc2insurance VARCHAR(255) DEFAULT NULL, CHANGE rc_receipt rc_receipt VARCHAR(255) DEFAULT NULL, CHANGE prevention_service_contract prevention_service_contract VARCHAR(255) DEFAULT NULL, CHANGE prevention_service_invoice prevention_service_invoice VARCHAR(255) DEFAULT NULL, CHANGE prevention_service_receipt prevention_service_receipt VARCHAR(255) DEFAULT NULL, CHANGE occupational_accidents_insurance occupational_accidents_insurance VARCHAR(255) DEFAULT NULL, CHANGE occupational_receipt occupational_receipt VARCHAR(255) DEFAULT NULL, CHANGE labor_risk_assessment labor_risk_assessment VARCHAR(255) DEFAULT NULL, CHANGE security_plan security_plan VARCHAR(255) DEFAULT NULL, CHANGE rea_certificate rea_certificate VARCHAR(255) DEFAULT NULL, CHANGE oil_certificate oil_certificate VARCHAR(255) DEFAULT NULL, CHANGE gencat_payment_certificate gencat_payment_certificate VARCHAR(255) DEFAULT NULL, CHANGE deeds_of_powers deeds_of_powers VARCHAR(255) DEFAULT NULL, CHANGE iae_registration iae_registration VARCHAR(255) DEFAULT NULL, CHANGE iae_receipt iae_receipt VARCHAR(255) DEFAULT NULL, CHANGE mutual_partnership mutual_partnership VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE collection_document_type CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE sit_reference sit_reference VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE work CHANGE service_id service_id INT DEFAULT NULL, CHANGE short_description short_description VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE service CHANGE vehicle_category_id vehicle_category_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE work_image CHANGE work_id work_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE contact_message CHANGE answer answer VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE complement CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_type CHANGE account account VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_unable_days CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE class_id class_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE transfer_account_id transfer_account_id INT DEFAULT NULL, CHANGE main_city_id main_city_id INT DEFAULT NULL, CHANGE secondary_city_id secondary_city_id INT DEFAULT NULL, CHANGE main_address main_address VARCHAR(255) DEFAULT NULL, CHANGE secondary_address secondary_address VARCHAR(255) DEFAULT NULL, CHANGE phone_number1 phone_number1 VARCHAR(255) DEFAULT NULL, CHANGE phone_number2 phone_number2 VARCHAR(255) DEFAULT NULL, CHANGE phone_number3 phone_number3 VARCHAR(255) DEFAULT NULL, CHANGE phone_number4 phone_number4 VARCHAR(255) DEFAULT NULL, CHANGE phone_number5 phone_number5 VARCHAR(255) DEFAULT NULL, CHANGE fax_number1 fax_number1 VARCHAR(255) DEFAULT NULL, CHANGE fax_number2 fax_number2 VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE www www VARCHAR(255) DEFAULT NULL, CHANGE discount discount DOUBLE PRECISION DEFAULT NULL, CHANGE code code INT DEFAULT NULL, CHANGE provider_reference provider_reference VARCHAR(255) DEFAULT NULL, CHANGE reference reference VARCHAR(255) DEFAULT NULL, CHANGE iva_tax_free iva_tax_free TINYINT(1) DEFAULT NULL, CHANGE iban iban VARCHAR(255) DEFAULT NULL, CHANGE swift swift VARCHAR(255) DEFAULT NULL, CHANGE bank_code bank_code VARCHAR(255) DEFAULT NULL, CHANGE office_number office_number VARCHAR(255) DEFAULT NULL, CHANGE control_digit control_digit VARCHAR(255) DEFAULT NULL, CHANGE account_number account_number VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_contact CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE care care VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE mobile mobile VARCHAR(255) DEFAULT NULL, CHANGE fax fax VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_order CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE provider_reference provider_reference VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_building_site CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE partner_class CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE sale_invoice_series CHANGE prefix prefix VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE city CHANGE province_id province_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE province CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE admin_user CHANGE default_enterprise_id default_enterprise_id INT DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL, CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT NULL, CHANGE date_of_birth date_of_birth DATETIME DEFAULT NULL, CHANGE firstname firstname VARCHAR(64) DEFAULT NULL, CHANGE lastname lastname VARCHAR(64) DEFAULT NULL, CHANGE website website VARCHAR(64) DEFAULT NULL, CHANGE biography biography VARCHAR(1000) DEFAULT NULL, CHANGE gender gender VARCHAR(1) DEFAULT NULL, CHANGE locale locale VARCHAR(8) DEFAULT NULL, CHANGE timezone timezone VARCHAR(64) DEFAULT NULL, CHANGE phone phone VARCHAR(64) DEFAULT NULL, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT NULL, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT NULL, CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT NULL, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT NULL, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT NULL, CHANGE main_image main_image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE operator_various_amount CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE units units INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT NULL, CHANGE price_unit price_unit DOUBLE PRECISION DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE operator_absence CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE operator_cheking CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE operator_absence_type CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE operator_checking_type CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE operator CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE enterprise_group_bounty_id enterprise_group_bounty_id INT DEFAULT NULL, CHANGE hour_cost hour_cost DOUBLE PRECISION DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE enterprise_mobile enterprise_mobile VARCHAR(255) DEFAULT NULL, CHANGE own_phone own_phone VARCHAR(255) DEFAULT NULL, CHANGE own_mobile own_mobile VARCHAR(255) DEFAULT NULL, CHANGE profile_photo_image profile_photo_image VARCHAR(255) DEFAULT NULL, CHANGE tax_identification_number_image tax_identification_number_image VARCHAR(255) DEFAULT NULL, CHANGE driving_license_image driving_license_image VARCHAR(255) DEFAULT NULL, CHANGE cranes_operator_license_image cranes_operator_license_image VARCHAR(255) DEFAULT NULL, CHANGE medical_check_image medical_check_image VARCHAR(255) DEFAULT NULL, CHANGE epis_image epis_image VARCHAR(255) DEFAULT NULL, CHANGE training_document_image training_document_image VARCHAR(255) DEFAULT NULL, CHANGE information_image information_image VARCHAR(255) DEFAULT NULL, CHANGE use_of_machinery_authorization_image use_of_machinery_authorization_image VARCHAR(255) DEFAULT NULL, CHANGE discharge_social_security_image discharge_social_security_image VARCHAR(255) DEFAULT NULL, CHANGE employment_contract_image employment_contract_image VARCHAR(255) DEFAULT NULL, CHANGE shoe_size shoe_size VARCHAR(255) DEFAULT NULL, CHANGE jerseyt_size jerseyt_size VARCHAR(255) DEFAULT NULL, CHANGE jacket_size jacket_size VARCHAR(255) DEFAULT NULL, CHANGE t_shirt_size t_shirt_size VARCHAR(255) DEFAULT NULL, CHANGE pant_size pant_size VARCHAR(255) DEFAULT NULL, CHANGE working_dress_size working_dress_size VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE operator_digital_tachograph CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE acl_object_identities CHANGE parent_object_identity_id parent_object_identity_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE acl_entries CHANGE object_identity_id object_identity_id INT UNSIGNED DEFAULT NULL, CHANGE field_name field_name VARCHAR(50) DEFAULT NULL');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE digital_tachograph (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, uploaded_date DATETIME NOT NULL, uploaded_file_name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT \'NULL\', INDEX IDX_EB2549C9584598A3 (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE digital_tachograph ADD CONSTRAINT FK_EB2549C9584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('DROP TABLE invoices_deliveynotes');
        $this->addSql('ALTER TABLE acl_entries CHANGE object_identity_id object_identity_id INT UNSIGNED DEFAULT NULL, CHANGE field_name field_name VARCHAR(50) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE acl_object_identities CHANGE parent_object_identity_id parent_object_identity_id INT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE activity_line CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE admin_user CHANGE default_enterprise_id default_enterprise_id INT DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT \'NULL\', CHANGE expires_at expires_at DATETIME DEFAULT \'NULL\', CHANGE confirmation_token confirmation_token VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE credentials_expire_at credentials_expire_at DATETIME DEFAULT \'NULL\', CHANGE date_of_birth date_of_birth DATETIME DEFAULT \'NULL\', CHANGE firstname firstname VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE lastname lastname VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE website website VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE biography biography VARCHAR(1000) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gender gender VARCHAR(1) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE locale locale VARCHAR(8) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE timezone timezone VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone phone VARCHAR(64) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE facebook_uid facebook_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE facebook_name facebook_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE facebook_data facebook_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE twitter_uid twitter_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE twitter_name twitter_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE twitter_data twitter_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE gplus_uid gplus_uid VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gplus_name gplus_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gplus_data gplus_data LONGTEXT DEFAULT \'NULL\' COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', CHANGE token token VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE two_step_code two_step_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE main_image main_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE city CHANGE province_id province_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE collection_document_type CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE sit_reference sit_reference VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE complement CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE contact_message CHANGE answer answer VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone phone VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE enterprise CHANGE city_id city_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone1 phone1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone2 phone2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone3 phone3 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE fax fax VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE www www VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE logo logo VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE deed_of_incorporation deed_of_incorporation VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE tax_identification_number_card tax_identification_number_card VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE tc1receipt tc1receipt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE tc2receipt tc2receipt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE ss_registration ss_registration VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE ss_payment_certificate ss_payment_certificate VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE rc1insurance rc1insurance VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE rc2insurance rc2insurance VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE rc_receipt rc_receipt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE prevention_service_contract prevention_service_contract VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE prevention_service_invoice prevention_service_invoice VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE prevention_service_receipt prevention_service_receipt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE occupational_accidents_insurance occupational_accidents_insurance VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE occupational_receipt occupational_receipt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE labor_risk_assessment labor_risk_assessment VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE security_plan security_plan VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE rea_certificate rea_certificate VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE oil_certificate oil_certificate VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE gencat_payment_certificate gencat_payment_certificate VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE deeds_of_powers deeds_of_powers VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE iae_registration iae_registration VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE iae_receipt iae_receipt VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE mutual_partnership mutual_partnership VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE enterprise_group_bounty CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE enterprise_holidays CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE enterprise_transfer_account CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE iban iban VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE swift swift VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE bank_code bank_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE office_number office_number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE control_digit control_digit VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE account_number account_number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE enterprise_group_bounty_id enterprise_group_bounty_id INT DEFAULT NULL, CHANGE hour_cost hour_cost DOUBLE PRECISION DEFAULT \'NULL\', CHANGE address address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE email email VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE enterprise_mobile enterprise_mobile VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE own_phone own_phone VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE own_mobile own_mobile VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE profile_photo_image profile_photo_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE tax_identification_number_image tax_identification_number_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE driving_license_image driving_license_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE cranes_operator_license_image cranes_operator_license_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE medical_check_image medical_check_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE epis_image epis_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE training_document_image training_document_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE information_image information_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE use_of_machinery_authorization_image use_of_machinery_authorization_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE discharge_social_security_image discharge_social_security_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE employment_contract_image employment_contract_image VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE shoe_size shoe_size VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE jerseyt_size jerseyt_size VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE jacket_size jacket_size VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE t_shirt_size t_shirt_size VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE pant_size pant_size VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE working_dress_size working_dress_size VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator_absence CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator_absence_type CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator_checking_type CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator_cheking CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator_digital_tachograph CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE operator_various_amount CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE units units INT DEFAULT NULL, CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE price_unit price_unit DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE class_id class_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE transfer_account_id transfer_account_id INT DEFAULT NULL, CHANGE main_city_id main_city_id INT DEFAULT NULL, CHANGE secondary_city_id secondary_city_id INT DEFAULT NULL, CHANGE main_address main_address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE secondary_address secondary_address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone_number1 phone_number1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone_number2 phone_number2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone_number3 phone_number3 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone_number4 phone_number4 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone_number5 phone_number5 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE fax_number1 fax_number1 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE fax_number2 fax_number2 VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE email email VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE www www VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE discount discount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE code code INT DEFAULT NULL, CHANGE provider_reference provider_reference VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE reference reference VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE iva_tax_free iva_tax_free TINYINT(1) DEFAULT \'NULL\', CHANGE iban iban VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE swift swift VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE bank_code bank_code VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE office_number office_number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE control_digit control_digit VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE account_number account_number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_building_site CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE address address VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone phone VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_class CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_contact CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE care care VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE phone phone VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE mobile mobile VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE fax fax VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE email email VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_order CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE provider_reference provider_reference VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_type CHANGE account account VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE partner_unable_days CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE province CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_delivery_note ADD sale_invoice_id INT DEFAULT NULL, CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE building_site_id building_site_id INT DEFAULT NULL, CHANGE order_id order_id INT DEFAULT NULL, CHANGE collection_document_id collection_document_id INT DEFAULT NULL, CHANGE activity_line_id activity_line_id INT DEFAULT NULL, CHANGE discount discount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE collection_term collection_term INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46AD4DD15B9 FOREIGN KEY (sale_invoice_id) REFERENCES sale_invoice (id)');
        $this->addSql('CREATE INDEX IDX_3FA6B46AD4DD15B9 ON sale_delivery_note (sale_invoice_id)');
        $this->addSql('ALTER TABLE sale_delivery_note_line CHANGE delivery_note_id delivery_note_id INT DEFAULT NULL, CHANGE units units DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total total DOUBLE PRECISION DEFAULT \'NULL\', CHANGE discount discount DOUBLE PRECISION DEFAULT \'NULL\', CHANGE description description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_invoice CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE series_id series_id INT DEFAULT NULL, CHANGE total total DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_invoice_series CHANGE prefix prefix VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_request CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE partner_id partner_id INT DEFAULT NULL, CHANGE invoice_to_id invoice_to_id INT DEFAULT NULL, CHANGE vehicle_id vehicle_id INT DEFAULT NULL, CHANGE operator_id operator_id INT DEFAULT NULL, CHANGE tariff_id tariff_id INT DEFAULT NULL, CHANGE attended_by_id attended_by_id INT DEFAULT NULL, CHANGE secondary_vehicle_id secondary_vehicle_id INT DEFAULT NULL, CHANGE contact_person_name contact_person_name VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE contact_person_phone contact_person_phone VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE height height INT DEFAULT NULL, CHANGE distance distance INT DEFAULT NULL, CHANGE weight weight DOUBLE PRECISION DEFAULT \'NULL\', CHANGE utensils utensils VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE end_service_time end_service_time TIME DEFAULT \'NULL\', CHANGE hour_price hour_price DOUBLE PRECISION DEFAULT \'NULL\', CHANGE minium_hours minium_hours DOUBLE PRECISION DEFAULT \'NULL\', CHANGE displacement displacement DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_request_has_delivery_note CHANGE sale_request_id sale_request_id INT DEFAULT NULL, CHANGE sale_delivery_note_id sale_delivery_note_id INT DEFAULT NULL, CHANGE reference reference VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE total_hours_morning total_hours_morning DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_hour_morning price_hour_morning DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_morning amount_morning DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_hours_afternoon total_hours_afternoon DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_hour_afternoon price_hour_afternoon DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_afternoon amount_afternoon DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_hours_night total_hours_night DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_hour_night price_hour_night DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_night amount_night DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_hours_early_morning total_hours_early_morning DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_hour_early_morning price_hour_early_morning DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_early_morning amount_early_morning DOUBLE PRECISION DEFAULT \'NULL\', CHANGE total_hours_displacement total_hours_displacement DOUBLE PRECISION DEFAULT \'NULL\', CHANGE price_hour_displacement price_hour_displacement DOUBLE PRECISION DEFAULT \'NULL\', CHANGE amount_displacement amount_displacement DOUBLE PRECISION DEFAULT \'NULL\', CHANGE iva_type iva_type DOUBLE PRECISION DEFAULT \'NULL\', CHANGE retention_type retention_type DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE sale_tariff CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE price_hour price_hour DOUBLE PRECISION DEFAULT \'NULL\', CHANGE minium_hours minium_hours DOUBLE PRECISION DEFAULT \'NULL\', CHANGE minium_holiday_hours minium_holiday_hours DOUBLE PRECISION DEFAULT \'NULL\', CHANGE displacement displacement DOUBLE PRECISION DEFAULT \'NULL\', CHANGE increase_for_holidays increase_for_holidays DOUBLE PRECISION DEFAULT \'NULL\', CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE service CHANGE vehicle_category_id vehicle_category_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vehicle CHANGE vehicle_category_id vehicle_category_id INT DEFAULT NULL, CHANGE enterprise_id enterprise_id INT DEFAULT NULL, CHANGE short_description short_description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE link link VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE attatchment_pdf attatchment_pdf VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vehicle_category CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vehicle_checking CHANGE vehicle_id vehicle_id INT DEFAULT NULL, CHANGE type_id type_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vehicle_checking_type CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE vehicle_digital_tachograph CHANGE vehicle_id vehicle_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE work CHANGE service_id service_id INT DEFAULT NULL, CHANGE short_description short_description VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE work_image CHANGE work_id work_id INT DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
    }
}
