services:
    app.service_repository:
        class: AppBundle\Repository\ServiceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Service
    app.vehicle_category_repository:
        class: AppBundle\Repository\VehicleCategoryRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:VehicleCategory
    app.work_repository:
        class: AppBundle\Repository\WorkRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Work
    app.complement_repository:
        class: AppBundle\Repository\ComplementRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Complement
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:User
    app.operator_repository:
        class: AppBundle\Repository\OperatorRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Operator
    app.enterprise_repository:
        class: AppBundle\Repository\EnterpriseRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Enterprise
    app.enterprise_group_bounty_repository:
        class: AppBundle\Repository\EnterpriseGroupBountyRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:EnterpriseGroupBounty
    app.enterprise_transfer_account_repository:
        class: AppBundle\Repository\EnterpriseTransferAccountRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:EnterpriseTransferAccount
    app.enterprise_holidays_repository:
        class: AppBundle\Repository\EnterpriseHolidaysRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:EnterpriseHolidays
    app.operator_checking_repository:
        class: AppBundle\Repository\OperatorCheckingRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:OperatorChecking
    app.operator_checking_type_repository:
        class: AppBundle\Repository\OperatorCheckingTypeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:OperatorCheckingType
    app.operator_absence_repository:
        class: AppBundle\Repository\OperatorAbsenceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:OperatorAbsence
    app.operator_absence_type_repository:
        class: AppBundle\Repository\OperatorAbsenceTypeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:OperatorAbsenceType
    app.vehicle_repository:
        class: AppBundle\Repository\VehicleRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Vehicle
    app.vehicle_checking_type_repository:
        class: AppBundle\Repository\VehicleCheckingTypeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:VehicleCheckingType
    app.vehicle_checking_repository:
        class: AppBundle\Repository\VehicleCheckingRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:VehicleChecking
    app.partner_repository:
        class: AppBundle\Repository\PartnerRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Partner
    app.partner_class_repository:
        class: AppBundle\Repository\PartnerClassRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:PartnerClass
    app.partner_type_repository:
        class: AppBundle\Repository\PartnerTypeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:PartnerType
    app.partner_building_site_repository:
        class: AppBundle\Repository\PartnerBuildingSiteRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:PartnerBuildingSite
    app.partner_order_repository:
        class: AppBundle\Repository\PartnerOrderRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:PartnerOrder
    app.city_repository:
        class: AppBundle\Repository\CityRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:City
    app.sale_tariff_repository:
        class: AppBundle\Repository\SaleTariffRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:SaleTariff
    app.collection_document_type_repository:
        class: AppBundle\Repository\CollectionDocumentTypeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:CollectionDocumentType
    app.activity_line_repository:
        class: AppBundle\Repository\ActivityLineRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:ActivityLine
    app.sale_invoice_series_repository:
        class: AppBundle\Repository\SaleInvoiceSeriesRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:SaleInvoiceSeries
    app.sale_invoice_repository:
        class: AppBundle\Repository\SaleInvoiceRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:SaleInvoice
    app.sale_request_repository:
        class: AppBundle\Repository\SaleRequestRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:SaleRequest
    app.sale_delivery_note_repository:
        class: AppBundle\Repository\SaleDeliveryNoteRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:SaleDeliveryNote
    app.repositories_manager:
        class: AppBundle\Manager\RepositoriesManager
        arguments:
            - "@app.service_repository"
            - "@app.vehicle_category_repository"
            - "@app.user_repository"
            - "@app.operator_repository"
            - "@app.enterprise_repository"
            - "@app.enterprise_group_bounty_repository"
            - "@app.enterprise_transfer_account_repository"
            - "@app.enterprise_holidays_repository"
            - "@app.operator_checking_repository"
            - "@app.operator_checking_type_repository"
            - "@app.operator_absence_type_repository"
            - "@app.operator_absence_repository"
            - "@app.vehicle_repository"
            - "@app.vehicle_checking_type_repository"
            - "@app.vehicle_checking_repository"
            - "@app.partner_repository"
            - "@app.partner_class_repository"
            - "@app.partner_type_repository"
            - "@app.city_repository"
            - "@app.sale_tariff_repository"
            - "@app.partner_building_site_repository"
            - "@app.partner_order_repository"
            - "@app.collection_document_type_repository"
            - "@app.activity_line_repository"
            - "@app.sale_invoice_series_repository"
            - "@app.sale_request_repository"
            - "@app.sale_delivery_note_repository"

